projects:
  apils:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: snu26cfbtfbd3l7hwsubn7246y
      endpoints:
        prod: >-
          https://nnvyla3odfbqxdqgamozglabp4.appsync-api.us-east-1.amazonaws.com/graphql
