//userInfo actions
export const LOAD_USER_INFO = "LOAD_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
//appModuleAccess actions
export const LOAD_APPMODULE_ACCESS = "LOAD_APPMODULE_ACCESS";
//cvReview actions
export const LIST_CVREVIEWS_SUCCESS = "LIST_CVREVIEWS_SUCCESS";
export const CREATE_CVREVIEW_SUCCESS = "CREATE_CVREVIEW_SUCCESS";
export const UPDATE_CVREVIEW_SUCCESS = "UPDATE_CVREVIEW_SUCCESS";
//pricing plans actions
export const LIST_PRICINGPLANS_SUCCESS = "LIST_PRICINGPLANS_SUCCESS";